const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');let browser;
const out=path.join(__dirname,'age12');fs.mkdirSync(out,{recursive:true});
(async()=>{
 browser=await chromium.launch({channel:'msedge',headless:true});const p=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:4173/find_mom_3d/');await p.waitForFunction(()=>window.meadowGame);
 const shot=n=>p.screenshot({path:path.join(out,n+'.png')});
 async function talk(){for(let n=0;n<50&&await p.evaluate(()=>meadowGame.state.mode==='dialogue');n++)await p.locator('#dialogue-next').click();}
 async function seed(chapter,extra={}){await p.evaluate(({chapter,extra})=>{const g=meadowGame,s=Meadow.Progress.fresh();s.entryChapter=s.chapter=chapter;s.prologueSeen=true;for(const [k,v] of Object.entries(extra)){if(v&&typeof v==='object'&&!Array.isArray(v))Object.assign(s[k],v);else s[k]=v;}g.saved=s;g.start(true);},{chapter,extra});}
 async function pause(){await p.keyboard.press('Escape');const t=await p.evaluate(()=>meadowGame.time);await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>meadowGame.time),t);await p.locator('#resume-btn').click();}
 async function steerLoop(read,done,limit=70000){let held=null;const end=Date.now()+limit;while(!await p.evaluate(done)&&Date.now()<end){const q=await p.evaluate(read),key=Math.abs(q.x-q.t)<.025?null:q.t>q.x?'ArrowRight':'ArrowLeft';if(key!==held){if(held)await p.keyboard.up(held);if(key)await p.keyboard.down(key);held=key;}if(q.shoot)await p.keyboard.press('e');await p.waitForTimeout(35);}if(held)await p.keyboard.up(held);assert(await p.evaluate(done),'steering challenge timed out');}
 await seed(1,{ribbon:true,metRabbit:true,metHedgehog:true});await p.evaluate(()=>meadowGame.challenges.open('wind'));await shot('wind-desktop');assert.equal(await p.locator('[data-tile]').count(),16);
 const before=await p.evaluate(()=>[...meadowGame.state.windTurns]);await p.locator('[data-tile="1"]').click();const after=await p.evaluate(()=>meadowGame.state.windTurns);assert.equal(after[1],(before[1]+1)%4);assert.equal(after[10],(before[10]+3)%4);
 for(let i=0;i<16;i++){const turns=await p.evaluate(i=>(CONFIG.WIND_SOLUTION[i]-meadowGame.state.windTurns[i]+4)%4,i);for(let j=0;j<turns;j++)await p.locator(`[data-tile="${i}"]`).click();}
 await p.locator('#puzzle-submit').click();await talk();assert(await p.evaluate(()=>meadowGame.state.windSolved));
 await p.evaluate(()=>{meadowGame.state.flowers=['sun','heart','star'];meadowGame.challenges.open('lamp');});await shot('lamp-desktop');
 const solutions=await p.evaluate(()=>{function perm(a){return a.length?a.flatMap((x,i)=>perm(a.filter((_,j)=>j!==i)).map(v=>[x,...v])):[[]];}return perm(CONFIG.LAMP_ITEMS.map(v=>v.id)).filter(a=>Meadow.PuzzleRules.lampSolved(a));});assert.equal(solutions.length,1);
 for(const [i,id] of solutions[0].entries()){await p.locator(`[data-item="${id}"]`).click();await p.locator(`[data-slot="${i}"]`).click();}await p.locator('#puzzle-submit').click();await talk();assert(await p.evaluate(()=>meadowGame.state.lit));
 console.log('PASS chapter 1: 16 linked pipes solved by clicks; 720 six-item permutations have one solution; actual UI completes lamp');
 await seed(2,{forest:{metOwl:true}});await p.evaluate(()=>meadowGame.song.open());
 for(let round=0;round<3;round++){await p.locator('#song-replay').click();await p.waitForFunction(()=>meadowGame.song.ready);const expected=await p.evaluate(()=>Meadow.SongPuzzle.expected(meadowGame.state.forest.round));assert.equal(expected.length,6+round);for(const id of expected)await p.locator(`[data-note="${id}"]`).click();assert.equal(await p.locator('#song-input .score-note').count(),expected.length);await p.locator('#song-next').click();}await talk();assert.equal(await p.evaluate(()=>meadowGame.state.forest.round),3);
 await p.evaluate(()=>meadowGame.trials.start('gust'));await p.locator('#action-start').click();await pause();await shot('gust');
 const patterns=[[0],[2],[1],[0,1],[1,2],[0,2],[1,2],[0,1],[0,2],[0,1],[0,2],[1,2],[0,2],[1,2],[0,1],[1,2],[0,1],[0,2]],end=Date.now()+80000;
 while(await p.evaluate(()=>meadowGame.trials.active)&&Date.now()<end){const q=await p.evaluate(()=>({stage:meadowGame.trials.stage,lane:meadowGame.trials.lane})),safe=[0,1,2].find(i=>!patterns[q.stage].includes(i));if(q.lane!==safe){const reversed=q.stage>=12&&q.stage%3===2,direction=(safe>q.lane?1:-1)*(reversed?-1:1);await p.keyboard.press(direction>0?'ArrowRight':'ArrowLeft');}await p.waitForTimeout(40);}assert.equal(await p.evaluate(()=>meadowGame.state.forest.gustStage),6);await talk();
 await p.evaluate(()=>{const g=meadowGame;Object.assign(g.state.forest,{reunited:true,separated:true,routeKnown:true});g.trials.start('dash');});await p.locator('#action-start').click();await shot('dash');const until=Date.now()+55000;while(await p.evaluate(()=>meadowGame.trials.active)&&Date.now()<until){const q=await p.evaluate(()=>({stage:meadowGame.trials.stage,lane:meadowGame.trials.lane,running:meadowGame.trials.dashRunning,queued:meadowGame.trials.queued})),safe=[0,2,1,2,0,1,0,2,1][q.stage];if(!q.running){if(q.lane!==safe)await p.keyboard.press(safe>q.lane?'ArrowRight':'ArrowLeft');else if(!q.queued)await p.keyboard.press('e');}await p.waitForTimeout(35);}assert.equal(await p.evaluate(()=>meadowGame.state.forest.dashStage),3);await talk();console.log('PASS chapter 2: longer rule-transform melodies, 18 gusts including reversed controls, nine lane-and-run segments');
 await seed(3,{valley:{metBeaver:true}});await p.evaluate(()=>meadowGame.expedition.start('bridge'));await p.locator('#journey-start').click();await shot('bridge');
 for(let i=0;i<9;i++){await p.waitForFunction(()=>{const e=meadowGame.expedition;return e.cooldown===0&&Math.abs(e.needle-e.bridgeSettings().center)<.025;});await p.keyboard.press('e');}await talk();assert.equal(await p.evaluate(()=>meadowGame.state.valley.bridge),3);
 await p.evaluate(()=>meadowGame.expedition.start('raft'));await p.locator('#journey-start').click();await p.keyboard.press('e');assert(await p.evaluate(()=>meadowGame.expedition.braking));await pause();await shot('raft');
 await steerLoop(()=>({x:meadowGame.expedition.raftX,t:meadowGame.expedition.gateCenter}),()=>!meadowGame.expedition.active);await talk();assert.equal(await p.evaluate(()=>meadowGame.state.valley.raft),4);console.log('PASS chapter 3: nine arithmetic/timing strikes, brake toggle and all 12 moving water gates');
 await seed(4,{hill:{metSquirrel:true}});
 for(const beacon of ['hope','memory','courage']){await p.evaluate(id=>meadowGame.expedition.start('star',id),beacon);await p.locator('#journey-start').click();await p.keyboard.press('e');assert.equal(await p.evaluate(()=>meadowGame.state.hill.lights.length),['hope','memory','courage'].indexOf(beacon));await shot('star-'+beacon);await steerLoop(()=>{const e=meadowGame.expedition;return {x:e.aim,t:e.target,shoot:e.focus>=2.8&&e.aligned&&e.exposure&&e.cooldown===0};},()=>!meadowGame.expedition.active,70000);await talk();}assert.equal(await p.evaluate(()=>meadowGame.state.hill.lights.length),3);
 await p.evaluate(()=>meadowGame.story.interact('signal'));await p.waitForFunction(()=>meadowGame.state.mode==='dialogue');await talk();await p.locator('#journey-start').click();await shot('escort');await steerLoop(()=>({x:meadowGame.expedition.escortX,t:meadowGame.expedition.gateCenter-.2}),()=>!meadowGame.expedition.active,60000);assert.equal(await p.evaluate(()=>meadowGame.state.hill.escort),3);await p.waitForFunction(()=>meadowGame.state.mode==='dialogue');await talk();assert(await p.evaluate(()=>meadowGame.state.hill.reunited));console.log('PASS chapter 4: nine timed exposures, nine moving/feint attacks, mother protected through gate and reunion');
 const migration=await p.evaluate(()=>{const s=Meadow.Progress.fresh();Object.assign(s,{version:5,chapter:1,ribbon:true,metRabbit:true,metHedgehog:true,windSolved:true,windTurns:[1,1,2,1,1,3,0,1,1],flowers:['sun','heart','star'],arrangement:['ribbon','sun','heart','star'],lit:true,completed:true});Meadow.Progress.write(s);return Meadow.Progress.read();});assert(migration.completed&&migration.version===6);assert.equal(migration.windTurns.length,16);assert.equal(migration.arrangement.length,6);
 assert.deepEqual(errors,[]);console.log('PASS legacy save migration; no browser runtime errors');await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1);});
