const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');let browser;
(async()=>{
 browser=await chromium.launch({channel:'msedge',headless:true});const p=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:4173/find_mom_3d/');await p.waitForFunction(()=>window.meadowGame);
 async function seed(c){await p.evaluate(c=>{const g=meadowGame,s=Meadow.Progress.fresh();s.chapter=c;s.entryChapter=4;s.prologueSeen=true;g.saved=s;g.start(true);g.saveProgress();},c);}
 async function near(id){const found=await p.evaluate(id=>{const g=meadowGame,target=g.interactions.candidates().find(o=>o.id===id);if(!target)return false;for(const r of [1.25,1.65,.95])for(let i=0;i<24;i++){const a=i*Math.PI/12,x=target.position.x+Math.sin(a)*r,z=target.position.z+Math.cos(a)*r;if(!g.world.canWalk(x,z))continue;g.player.setPosition(x,z);g.interactions.update();if(g.interactions.current?.id!==id)continue;g.view.update(1,false,true);return true;}return false;},id);assert(found,'no interaction position for '+id);await p.waitForTimeout(80);assert.equal(await p.evaluate(()=>meadowGame.interactions.current?.id),id);}
 const main=()=>p.evaluate(()=>{const {playgrounds,mode,checkpoint,chapter,visited,...s}=meadowGame.state;return JSON.stringify(s);});
 for(let chapter=1;chapter<=4;chapter++){
  await seed(chapter);const baseline=await main();
  const placed=await p.evaluate(()=>{
   const g=meadowGame,w=g.world,step=.5,width=165,height=177,walk=new Uint8Array(width*height),seen=new Uint8Array(walk.length),pos=i=>({x:i%width*step-41,z:Math.floor(i/width)*step-45});
   for(let i=0;i<walk.length;i++){const p=pos(i);walk[i]=w.canWalk(p.x,p.z)?1:0;}const queue=[112*width+82];seen[queue[0]]=1;
   for(let head=0;head<queue.length;head++){const i=queue[head];for(const n of [i-1,i+1,i-width,i+width]){if(n<0||n>=walk.length||seen[n]||!walk[n]||Math.abs(n%width-i%width)>1)continue;seen[n]=1;queue.push(n);}}
   return {locals:w.locals.length,items:w.playground.items.length,unreachable:[...w.locals,...w.playground.items].filter(o=>!queue.some(i=>{const p=pos(i);return Math.hypot(p.x-o.mesh.position.x,p.z-o.mesh.position.z)<1.9;})).map(o=>o.id),voiced:w.locals.every((n,i)=>[...Meadow.Sandbox.lines[i],Meadow.Sandbox.lines[1][1]].every(text=>Meadow.VoiceCatalog.some(row=>row.name===n.name&&row.text===text)))};
  });assert.equal(placed.locals,4);assert.equal(placed.items,14);assert.deepEqual(placed.unreachable,[]);assert(placed.voiced);
  const parcel=await p.evaluate(()=>meadowGame.world.playground.items.find(o=>o.kind==='parcel').id);await near(parcel);await p.keyboard.press('e');assert.equal(await p.evaluate(()=>meadowGame.sandbox.held?.id),parcel);await p.waitForTimeout(100);assert(await p.evaluate(()=>meadowGame.sandbox.held.position.y>.8));
  await p.evaluate(()=>{meadowGame.state.mode='journey';});await p.waitForTimeout(80);assert(await p.evaluate(()=>!!meadowGame.sandbox.held&&!meadowGame.sandbox.held.mesh.visible));await p.evaluate(()=>{meadowGame.state.mode='playing';});await p.waitForTimeout(80);assert(await p.evaluate(()=>meadowGame.sandbox.held.mesh.visible));
  await near('local-0');await p.keyboard.press('e');assert(await p.evaluate(()=>!!meadowGame.sandbox.held));assert.deepEqual(await p.evaluate(()=>meadowGame.sandbox.progress().parcels),[]);
  await p.keyboard.press('q');assert.equal(await p.evaluate(()=>meadowGame.sandbox.held?.id||null),null);assert(await p.evaluate(id=>{const g=meadowGame,o=g.world.playground.items.find(o=>o.id===id);return o.position.distanceTo(g.player.mesh.position)<1.3&&g.world.canWalk(o.position.x,o.position.z);},parcel));
  await near(parcel);await p.keyboard.press('e');await near('local-1');await p.keyboard.press('e');assert.deepEqual(await p.evaluate(()=>meadowGame.sandbox.progress().parcels),[0]);assert.equal(await p.evaluate(()=>meadowGame.sandbox.held?.id||null),null);
  const planter=await p.evaluate(()=>meadowGame.world.playground.items.find(o=>o.kind==='planter').id);await near(planter);await p.keyboard.press('e');assert.deepEqual(await p.evaluate(()=>meadowGame.sandbox.progress().flowers),[0]);
  assert.equal(await main(),baseline,'sandbox must never award or erase main-story progress');
  const before=await p.evaluate(()=>meadowGame.sandbox.progress());await p.reload();await p.waitForFunction(()=>window.meadowGame);await p.locator('#start-btn').click();assert.deepEqual(await p.evaluate(()=>meadowGame.sandbox.progress()),before);
  assert(await p.evaluate(()=>{const p=meadowGame.world.playground;return !p.items.find(o=>o.kind==='parcel'&&o.number===0).mesh.visible&&p.items.find(o=>o.kind==='planter').flowers.scale.x===1;}));
  console.log('PASS chapter '+chapter+': reachable 4 NPCs / 14 props, all voices, delivery, wrong recipient, drop, flowering and save');
 }
 await seed(1);
 // A shot uses the real interaction key and frame-based collision/goal handling.
 await p.evaluate(()=>{const g=meadowGame,b=g.world.playground.ball;g.player.setPosition(b.position.x,b.position.z+1.5);g.view.update(1,false,true);g.interactions.update();});assert.equal(await p.evaluate(()=>meadowGame.interactions.current?.item?.kind),'ball');await p.keyboard.press('e');await p.waitForFunction(()=>meadowGame.sandbox.progress().goals===1);await p.waitForTimeout(1600);assert.equal(await p.evaluate(()=>meadowGame.sandbox.progress().goals),1);
 const crate=await p.evaluate(()=>meadowGame.world.playground.items.find(o=>o.kind==='crate').id);await near(crate);const original=await p.evaluate(id=>{const o=meadowGame.world.playground.items.find(o=>o.id===id);return o.position.toArray();},crate);await p.keyboard.press('e');await p.waitForTimeout(450);assert(await p.evaluate(({id,original})=>meadowGame.world.playground.items.find(o=>o.id===id).position.distanceTo(new THREE.Vector3(...original))>.2,{id:crate,original}));
 await p.evaluate(id=>{const g=meadowGame,o=g.world.playground.items.find(o=>o.id===id);g.player.setPosition(o.position.x,o.position.z+1.1);},crate);const startPush=await p.evaluate(id=>meadowGame.world.playground.items.find(o=>o.id===id).position.z,crate);await p.keyboard.down('ArrowUp');await p.waitForTimeout(600);await p.keyboard.up('ArrowUp');assert(await p.evaluate(({id,z})=>meadowGame.world.playground.items.find(o=>o.id===id).position.z<z-.3,{id:crate,z:startPush}));
 console.log('PASS real goal, no duplicate score, kick and body-push physics');
 // Pausing freezes moving props as well as residents.
 await near(crate);await p.keyboard.press('e');await p.keyboard.press('Escape');const frozen=await p.evaluate(()=>meadowGame.world.playground.items.map(o=>o.position.toArray()));await p.waitForTimeout(350);assert.deepEqual(await p.evaluate(()=>meadowGame.world.playground.items.map(o=>o.position.toArray())),frozen);await p.locator('#resume-btn').click();
 async function distance(){await p.evaluate(()=>meadowGame.player.setPosition(0,15));await p.keyboard.down('ArrowDown');await p.waitForTimeout(700);await p.keyboard.up('ArrowDown');return p.evaluate(()=>meadowGame.player.mesh.position.z-15);}
 const foot=await distance();const scooter=await p.evaluate(()=>meadowGame.world.playground.scooter.id);await near(scooter);await p.keyboard.press('e');assert(await p.evaluate(()=>!!meadowGame.sandbox.riding));const ride=await distance();assert(ride>foot*1.25,JSON.stringify({foot,ride}));await p.keyboard.press('q');assert.equal(await p.evaluate(()=>meadowGame.sandbox.riding?.id||null),null);assert.equal(await p.evaluate(()=>meadowGame.player.mesh.position.y),0);
 await near(scooter);await p.keyboard.press('e');await p.evaluate(()=>{meadowGame.state.mode='puzzle';});await p.waitForTimeout(80);assert.equal(await p.evaluate(()=>meadowGame.sandbox.riding?.id||null),null);assert.equal(await p.evaluate(()=>meadowGame.player.speedMultiplier),1);
 await seed(2);await near(await p.evaluate(()=>meadowGame.world.playground.scooter.id));await p.keyboard.press('e');await p.evaluate(()=>meadowGame.player.setPosition(0,-1.4));await p.keyboard.down('ArrowUp');await p.waitForTimeout(850);await p.keyboard.up('ArrowUp');assert(await p.evaluate(()=>meadowGame.player.mesh.position.z>=-2.4),'scooter crossed locked hedge');await p.keyboard.press('q');
 // The same collision implementation contains dynamic props at river banks.
 assert(await p.evaluate(()=>{const g=meadowGame,b=g.world.playground.ball;b.position.set(10,0,-5.1);b.vx=0;b.vz=-20;g.sandbox.move(b,0,-8);return b.position.z>=-5.35&&g.world.canWalk(b.position.x,b.position.z);}));
 console.log('PASS pause, scooter speed, dismount, challenge cleanup, locked gates and river collision');
 await seed(1);await p.evaluate(()=>{const g=meadowGame,n=g.world.locals[1];g.player.setPosition(n.mesh.position.x,n.mesh.position.z+1.6);n.dodgeAt=0;});await p.keyboard.down('ArrowUp');await p.waitForTimeout(300);await p.keyboard.up('ArrowUp');assert(await p.evaluate(()=>{const n=meadowGame.world.locals[1];return n.reaction>0&&n.reactionText==='！'&&Math.abs(n.collider.x-n.mesh.position.x)<.01;}));
 for(const kind of ['chime','pinwheel','drum','bench']){const id=await p.evaluate(kind=>meadowGame.world.playground.items.find(o=>o.kind===kind).id,kind);await near(id);await p.keyboard.press('e');if(kind==='bench'){assert(await p.evaluate(()=>!!meadowGame.sandbox.seated));await p.keyboard.down('ArrowRight');await p.waitForTimeout(100);await p.keyboard.up('ArrowRight');assert.equal(await p.evaluate(()=>meadowGame.sandbox.seated?.id||null),null);}else assert(await p.evaluate(id=>meadowGame.world.playground.items.find(o=>o.id===id).age>0,id));}
 const lastParcel=await p.evaluate(()=>meadowGame.world.playground.items.find(o=>o.kind==='parcel').id);await near(lastParcel);await p.keyboard.press('e');await p.evaluate(()=>meadowGame.travel.go(2));await p.waitForFunction(()=>meadowGame.state.chapter===2&&!meadowGame.travel.active);assert.equal(await p.evaluate(()=>meadowGame.sandbox.held?.id||null),null);assert.equal(await p.evaluate(()=>meadowGame.player.speedMultiplier),1);
 console.log('PASS NPC sidestep, bells/windmill/drum/bench and travel cleanup');
 const touch=await browser.newPage({hasTouch:true,isMobile:true,viewport:{width:390,height:844}});touch.on('pageerror',e=>errors.push(e.message));await touch.goto('http://127.0.0.1:4173/find_mom_3d/');await touch.waitForFunction(()=>window.meadowGame);await touch.evaluate(()=>{const g=meadowGame,s=Meadow.Progress.fresh();s.prologueSeen=true;g.saved=s;g.start(true);const o=g.world.playground.scooter;g.player.setPosition(o.position.x,o.position.z+1.1);g.view.update(1,false,true);g.interactions.update();});
 await touch.locator('#touch-action').tap();assert(await touch.evaluate(()=>!!meadowGame.sandbox.riding));
 assert(await touch.locator('#sandbox-release').isHidden(),'riding must not show two dismount prompts');await touch.locator('#touch-action').tap();assert.equal(await touch.evaluate(()=>!!meadowGame.sandbox.riding),false);
 await touch.evaluate(()=>{const g=meadowGame,o=g.world.playground.items.find(o=>o.kind==='parcel');g.player.setPosition(o.position.x,o.position.z+1.1);g.interactions.update();});await touch.locator('#touch-action').tap();assert(await touch.evaluate(()=>!!meadowGame.sandbox.held));
 for(const viewport of [{width:390,height:844},{width:844,height:390},{width:320,height:568}]){
  await touch.setViewportSize(viewport);await touch.waitForTimeout(100);const boxes=await touch.evaluate(()=>['sandbox-release','interaction-prompt','joystick','touch-action','minimap'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return {id,x:r.x,y:r.y,w:r.width,h:r.height};}));for(const r of boxes){if(r.id==='interaction-prompt'&&!r.w)continue;assert(r.w>0&&r.x>=0&&r.y>=0&&r.x+r.w<=viewport.width+1&&r.y+r.h<=viewport.height+1,JSON.stringify(r));}
  for(const control of boxes.slice(2)){const r=boxes[0];assert(r.x+r.w<=control.x||control.x+control.w<=r.x||r.y+r.h<=control.y||control.y+control.h<=r.y,JSON.stringify({release:r,control}));}
  await touch.screenshot({path:path.join(__dirname,`sandbox-touch-${viewport.width}.png`)});
 }
 await touch.evaluate(()=>{const g=meadowGame,o=g.world.playground.scooter;g.player.setPosition(o.position.x,o.position.z+1.1);g.interactions.update();});await touch.locator('#touch-action').tap();assert(await touch.evaluate(()=>!!meadowGame.sandbox.held&&!!meadowGame.sandbox.riding));await touch.locator('#touch-action').tap();assert(await touch.evaluate(()=>!!meadowGame.sandbox.held&&!meadowGame.sandbox.riding));
 await touch.locator('#sandbox-release').tap();assert.equal(await touch.evaluate(()=>meadowGame.sandbox.held?.id||null),null);assert.deepEqual(errors,[]);console.log('PASS touch borrowing/dismount, carry while riding and phone/landscape UI without overlapping controls');await browser.close();
})().catch(async error=>{console.error(error);if(browser)await browser.close();process.exit(1);});
